# Generated by Django 4.1.2 on 2023-04-24 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("number_of_choices", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("running", models.BooleanField(default=True)),
                ("number_of_votes", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                8, "This field must contain atleast 8 characters."
                            )
                        ],
                    ),
                ),
                ("admin", models.BooleanField(default=False)),
                (
                    "voted_in",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="voters", to="api.election"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("choice_id", models.IntegerField()),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="api.election",
                    ),
                ),
            ],
            options={
                "ordering": ["choice_id"],
            },
        ),
    ]
